return {
  require("manu.plugins.comment"),
  require("manu.plugins.completion_autopair"),
  require("manu.plugins.dressing"),
  -- require("manu.plugins.fidget"),
  require("manu.plugins.gitsigns"),
  -- require("manu.plugins.ibl"),
  require("manu.plugins.lsp"),
  require("manu.plugins.lualine"),
  require("manu.plugins.neoclip"),
  require("manu.plugins.neogit"),
  require("manu.plugins.nvim-surround"),
  -- require("manu.plugins.noice"),
  require("manu.plugins.notify"),
  require("manu.plugins.nordic"),
  require("manu.plugins.oil"),
  require("manu.plugins.projects"),
  require("manu.plugins.spectre"),
  require("manu.plugins.statuscol"),
  require("manu.plugins.telescope"),
  require("manu.plugins.treesitter"),
  require("manu.plugins.trouble"),
  require("manu.plugins.ufo"),
  require("manu.plugins.vim-fugitive"),
  require("manu.plugins.which-key"),
}
